// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/notification/notification.proto

package notificationpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Notification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Total         float64                `protobuf:"fixed64,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_proto_notification_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_proto_notification_notification_proto_rawDescGZIP(), []int{0}
}

func (x *Notification) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Notification) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CreateNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         float64                `protobuf:"fixed64,1,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNotificationRequest) Reset() {
	*x = CreateNotificationRequest{}
	mi := &file_proto_notification_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNotificationRequest) ProtoMessage() {}

func (x *CreateNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNotificationRequest.ProtoReflect.Descriptor instead.
func (*CreateNotificationRequest) Descriptor() ([]byte, []int) {
	return file_proto_notification_notification_proto_rawDescGZIP(), []int{1}
}

func (x *CreateNotificationRequest) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CreateNotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notification         *Notification                 `protobuf:"bytes,1,opt,name=notification,proto3" json:"notification,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNotificationResponse) Reset() {
	*x = CreateNotificationResponse{}
	mi := &file_proto_notification_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNotificationResponse) ProtoMessage() {}

func (x *CreateNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNotificationResponse.ProtoReflect.Descriptor instead.
func (*CreateNotificationResponse) Descriptor() ([]byte, []int) {
	return file_proto_notification_notification_proto_rawDescGZIP(), []int{2}
}

func (x *CreateNotificationResponse) GetNotification() *Notification {
	if x != nil {
		return x.Notification
	}
	return nil
}

type FindNotificationByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindNotificationByIDRequest) Reset() {
	*x = FindNotificationByIDRequest{}
	mi := &file_proto_notification_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindNotificationByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindNotificationByIDRequest) ProtoMessage() {}

func (x *FindNotificationByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindNotificationByIDRequest.ProtoReflect.Descriptor instead.
func (*FindNotificationByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_notification_notification_proto_rawDescGZIP(), []int{3}
}

func (x *FindNotificationByIDRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type FindNotificationByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notification         *Notification                 `protobuf:"bytes,1,opt,name=notification,proto3" json:"notification,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindNotificationByIDResponse) Reset() {
	*x = FindNotificationByIDResponse{}
	mi := &file_proto_notification_notification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindNotificationByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindNotificationByIDResponse) ProtoMessage() {}

func (x *FindNotificationByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_notification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindNotificationByIDResponse.ProtoReflect.Descriptor instead.
func (*FindNotificationByIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_notification_notification_proto_rawDescGZIP(), []int{4}
}

func (x *FindNotificationByIDResponse) GetNotification() *Notification {
	if x != nil {
		return x.Notification
	}
	return nil
}

type FindAllNotificationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllNotificationsRequest) Reset() {
	*x = FindAllNotificationsRequest{}
	mi := &file_proto_notification_notification_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllNotificationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllNotificationsRequest) ProtoMessage() {}

func (x *FindAllNotificationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_notification_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllNotificationsRequest.ProtoReflect.Descriptor instead.
func (*FindAllNotificationsRequest) Descriptor() ([]byte, []int) {
	return file_proto_notification_notification_proto_rawDescGZIP(), []int{5}
}

type FindAllNotificationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notifications        []*Notification               `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllNotificationsResponse) Reset() {
	*x = FindAllNotificationsResponse{}
	mi := &file_proto_notification_notification_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllNotificationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllNotificationsResponse) ProtoMessage() {}

func (x *FindAllNotificationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_notification_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllNotificationsResponse.ProtoReflect.Descriptor instead.
func (*FindAllNotificationsResponse) Descriptor() ([]byte, []int) {
	return file_proto_notification_notification_proto_rawDescGZIP(), []int{6}
}

func (x *FindAllNotificationsResponse) GetNotifications() []*Notification {
	if x != nil {
		return x.Notifications
	}
	return nil
}

type PatchNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Total         float64                `protobuf:"fixed64,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatchNotificationRequest) Reset() {
	*x = PatchNotificationRequest{}
	mi := &file_proto_notification_notification_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchNotificationRequest) ProtoMessage() {}

func (x *PatchNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_notification_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchNotificationRequest.ProtoReflect.Descriptor instead.
func (*PatchNotificationRequest) Descriptor() ([]byte, []int) {
	return file_proto_notification_notification_proto_rawDescGZIP(), []int{7}
}

func (x *PatchNotificationRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PatchNotificationRequest) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type PatchNotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notification         *Notification                 `protobuf:"bytes,1,opt,name=notification,proto3" json:"notification,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatchNotificationResponse) Reset() {
	*x = PatchNotificationResponse{}
	mi := &file_proto_notification_notification_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchNotificationResponse) ProtoMessage() {}

func (x *PatchNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_notification_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchNotificationResponse.ProtoReflect.Descriptor instead.
func (*PatchNotificationResponse) Descriptor() ([]byte, []int) {
	return file_proto_notification_notification_proto_rawDescGZIP(), []int{8}
}

func (x *PatchNotificationResponse) GetNotification() *Notification {
	if x != nil {
		return x.Notification
	}
	return nil
}

type DeleteNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNotificationRequest) Reset() {
	*x = DeleteNotificationRequest{}
	mi := &file_proto_notification_notification_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNotificationRequest) ProtoMessage() {}

func (x *DeleteNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_notification_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNotificationRequest.ProtoReflect.Descriptor instead.
func (*DeleteNotificationRequest) Descriptor() ([]byte, []int) {
	return file_proto_notification_notification_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteNotificationRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteNotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNotificationResponse) Reset() {
	*x = DeleteNotificationResponse{}
	mi := &file_proto_notification_notification_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNotificationResponse) ProtoMessage() {}

func (x *DeleteNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_notification_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNotificationResponse.ProtoReflect.Descriptor instead.
func (*DeleteNotificationResponse) Descriptor() ([]byte, []int) {
	return file_proto_notification_notification_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteNotificationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_notification_notification_proto protoreflect.FileDescriptor

const file_proto_notification_notification_proto_rawDesc = "" +
	"\n" +
	"\x17proto/notification/notification.proto\x12\x05notification\"-\n" +
	"\x05Notification\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x01R\x05total\"*\n" +
	"\x12CreateNotificationRequest\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x01R\x05total\"9\n" +
	"\x13CreateNotificationResponse\x12\"\n" +
	"\x05notification\x18\x01 \x01(\v2\f.notification.NotificationR\x05notification\"&\n" +
	"\x14FindNotificationByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\";\n" +
	"\x15FindNotificationByIDResponse\x12\"\n" +
	"\x05notification\x18\x01 \x01(\v2\f.notification.NotificationR\x05notification\"\x16\n" +
	"\x14FindAllNotificationsRequest\"=\n" +
	"\x15FindAllNotificationsResponse\x12$\n" +
	"\x06notifications\x18\x01 \x03(\v2\f.notification.NotificationR\x06notifications\"9\n" +
	"\x11PatchNotificationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x01R\x05total\"8\n" +
	"\x12PatchNotificationResponse\x12\"\n" +
	"\x05notification\x18\x01 \x01(\v2\f.notification.NotificationR\x05notification\"$\n" +
	"\x12DeleteNotificationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"/\n" +
	"\x13DeleteNotificationResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xf5\x02\n" +
	"\fNotificationService\x12D\n" +
	"\vCreateNotification\x12\x19.notification.CreateNotificationRequest\x1a\x1a.notification.CreateNotificationResponse\x12J\n" +
	"\rFindNotificationByID\x12\x1b.notification.FindNotificationByIDRequest\x1a\x1c.notification.FindNotificationByIDResponse\x12J\n" +
	"\rFindAllNotifications\x12\x1b.notification.FindAllNotificationsRequest\x1a\x1c.notification.FindAllNotificationsResponse\x12A\n" +
	"\n" +
	"PatchNotification\x12\x18.notification.PatchNotificationRequest\x1a\x19.notification.PatchNotificationResponse\x12D\n" +
	"\vDeleteNotification\x12\x19.notification.DeleteNotificationRequest\x1a\x1a.notification.DeleteNotificationResponseB3Z1github.com/MingPV/clean-go-template/proto/notificationpbb\x06proto3"

var (
	file_proto_notification_notification_proto_rawDescOnce sync.Once
	file_proto_notification_notification_proto_rawDescData []byte
)

func file_proto_notification_notification_proto_rawDescGZIP() []byte {
	file_proto_notification_notification_proto_rawDescOnce.Do(func() {
		file_proto_notification_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_notification_notification_proto_rawDesc), len(file_proto_notification_notification_proto_rawDesc)))
	})
	return file_proto_notification_notification_proto_rawDescData
}

var file_proto_notification_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_notification_notification_proto_goTypes = []any{
	(*Notification)(nil),                 // 0: notification.Notification
	(*CreateNotificationRequest)(nil),    // 1: notification.CreateNotificationRequest
	(*CreateNotificationResponse)(nil),   // 2: notification.CreateNotificationResponse
	(*FindNotificationByIDRequest)(nil),  // 3: notification.FindNotificationByIDRequest
	(*FindNotificationByIDResponse)(nil), // 4: notification.FindNotificationByIDResponse
	(*FindAllNotificationsRequest)(nil),  // 5: notification.FindAllNotificationsRequest
	(*FindAllNotificationsResponse)(nil), // 6: notification.FindAllNotificationsResponse
	(*PatchNotificationRequest)(nil),     // 7: notification.PatchNotificationRequest
	(*PatchNotificationResponse)(nil),    // 8: notification.PatchNotificationResponse
	(*DeleteNotificationRequest)(nil),    // 9: notification.DeleteNotificationRequest
	(*DeleteNotificationResponse)(nil),   // 10: notification.DeleteNotificationResponse
}
var file_proto_notification_notification_proto_depIdxs = []int32{
	0,  // 0: notification.CreateNotificationResponse.notification:type_name -> notification.Notification
	0,  // 1: notification.FindNotificationByIDResponse.notification:type_name -> notification.Notification
	0,  // 2: notification.FindAllNotificationsResponse.notifications:type_name -> notification.Notification
	0,  // 3: notification.PatchNotificationResponse.notification:type_name -> notification.Notification
	1,  // 4: notification.NotificationService.CreateNotification:input_type -> notification.CreateNotificationRequest
	3,  // 5: notification.NotificationService.FindNotificationByID:input_type -> notification.FindNotificationByIDRequest
	5,  // 6: notification.NotificationService.FindAllNotifications:input_type -> notification.FindAllNotificationsRequest
	7,  // 7: notification.NotificationService.PatchNotification:input_type -> notification.PatchNotificationRequest
	9,  // 8: notification.NotificationService.DeleteNotification:input_type -> notification.DeleteNotificationRequest
	2,  // 9: notification.NotificationService.CreateNotification:output_type -> notification.CreateNotificationResponse
	4,  // 10: notification.NotificationService.FindNotificationByID:output_type -> notification.FindNotificationByIDResponse
	6,  // 11: notification.NotificationService.FindAllNotifications:output_type -> notification.FindAllNotificationsResponse
	8,  // 12: notification.NotificationService.PatchNotification:output_type -> notification.PatchNotificationResponse
	10, // 13: notification.NotificationService.DeleteNotification:output_type -> notification.DeleteNotificationResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_notification_notification_proto_init() }
func file_proto_notification_notification_proto_init() {
	if File_proto_notification_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_notification_notification_proto_rawDesc), len(file_proto_notification_notification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_notification_notification_proto_goTypes,
		DependencyIndexes: file_proto_notification_notification_proto_depIdxs,
		MessageInfos:      file_proto_notification_notification_proto_msgTypes,
	}.Build()
	File_proto_notification_notification_proto = out.File
	file_proto_notification_notification_proto_goTypes = nil
	file_proto_notification_notification_proto_depIdxs = nil
}